/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EquipmentRouteImport } from './routes/equipment'
import { Route as RigRouteImport } from './routes/rig'
import { Route as ApiSceneRouteImport } from './routes/api.scene'
import { Route as AssetsSplatRouteImport } from './routes/assets.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipmentRoute = EquipmentRouteImport.update({
  id: '/equipment',
  path: '/equipment',
  getParentRoute: () => rootRouteImport,
} as any)
const RigRoute = RigRouteImport.update({
  id: '/rig',
  path: '/rig',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSceneRoute = ApiSceneRouteImport.update({
  id: '/api/scene',
  path: '/api/scene',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsSplatRoute = AssetsSplatRouteImport.update({
  id: '/assets/$',
  path: '/assets/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/equipment': typeof EquipmentRoute
  '/rig': typeof RigRoute
  '/api/scene': typeof ApiSceneRoute
  '/assets/$': typeof AssetsSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/equipment': typeof EquipmentRoute
  '/rig': typeof RigRoute
  '/api/scene': typeof ApiSceneRoute
  '/assets/$': typeof AssetsSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/equipment': typeof EquipmentRoute
  '/rig': typeof RigRoute
  '/api/scene': typeof ApiSceneRoute
  '/assets/$': typeof AssetsSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/equipment' | '/rig' | '/api/scene' | '/assets/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/equipment' | '/rig' | '/api/scene' | '/assets/$'
  id: '__root__' | '/' | '/equipment' | '/rig' | '/api/scene' | '/assets/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EquipmentRoute: typeof EquipmentRoute
  RigRoute: typeof RigRoute
  ApiSceneRoute: typeof ApiSceneRoute
  AssetsSplatRoute: typeof AssetsSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipment': {
      id: '/equipment'
      path: '/equipment'
      fullPath: '/equipment'
      preLoaderRoute: typeof EquipmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rig': {
      id: '/rig'
      path: '/rig'
      fullPath: '/rig'
      preLoaderRoute: typeof RigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/scene': {
      id: '/api/scene'
      path: '/api/scene'
      fullPath: '/api/scene'
      preLoaderRoute: typeof ApiSceneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets/$': {
      id: '/assets/$'
      path: '/assets/$'
      fullPath: '/assets/$'
      preLoaderRoute: typeof AssetsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EquipmentRoute: EquipmentRoute,
  RigRoute: RigRoute,
  ApiSceneRoute: ApiSceneRoute,
  AssetsSplatRoute: AssetsSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
